language: cpp

before_install:
 - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
 - sudo apt-get -qq update
 - sudo apt-get install -y libgtest-dev cmake unzip software-properties-common libboost-dev
 - sudo wget https://github.com/google/googletest/archive/master.zip
 - sudo unzip master.zip && sudo rm -f master.zip
 - cd googletest-master/googletest
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a include/gtest /usr/include
 - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"

script:
 - cmake .
 - cmake --build .
 - cmake --build . --target test

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
