language: cpp

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y cmake 
 - cd "${TRAVIS_BUILD_DIR}"

script:
- cmake .
- cmake --build .
- cmake --build . --target package

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uantik9:$BINTRAY_API_KEY \
    "https://api.bintray.com/content/antik9/HelloWorld/allocator/$TRAVIS_BUILD_NUMBER/allocator-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  on:
      branch: allocator
